### ISSUE TITLE
Ошибка запуска приложения

### ISSUE THREAD

**Issue by romhaberman** [romhaberman/Docker#1]
После запуска db-api.jar в терминале ошибка запуска приложения:

![ошибка при старте](https://github.com/user-attachments/assets/410c095c-ead9-4dfd-a743-a8ea54d8def6)

Антивирус и брэндмаур отключал на время, ситуация не изменилась, постгрес на ноутбуке локально не установлен.
Контейнер перезапускал, папку dadat удалял:

![docker down](https://github.com/user-attachments/assets/398b87d4-27cd-45c4-80a8-7b34844b2020)

![Сервер запущен и готов](https://github.com/user-attachments/assets/dbfe0928-49d1-4311-a3a4-831bb703cb92)

**Comment by andrew-pahomov** [comment]
Добрый день          

Вы используете неправильное имя пропертис файла, правильное - application.properties
